#!/usr/bin/env ruby

# Daemons sets pwd to /, so we have to explicitly set RAILS_ROOT
RAILS_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))

require 'rubygems'
require 'active_support'
require 'apn'
require 'apn/jobs/resque_notification_job'
require 'apn/sender_daemon'
require File.expand_path('../../config/initializers/apn_sender_hacks', __FILE__)

APN::SenderDaemon.new(ARGV).daemonize
