#!/usr/bin/env ruby

require 'rubygems'
require File.expand_path('../../config/environment', __FILE__)
require 'storify_client'

limit = (ARGV[0] || 5).to_i
stories = StorifyClient.fetch_story(limit)
if stories.length > 1 # success
  StorifyStory.delete_all

  stories.each do |s|
    StorifyStory.create! s
  end
  puts "Created #{stories.length} stories"
end
puts "done."
